//
// Created by tobias on 19.01.26.
//

#ifndef MESSAGETYPE_H
#define MESSAGETYPE_H
enum CanMessageType {
   NODE_INFO_REQUEST = 0,
   NODE_INFO_ANOUNCEMENT = 1,
   INFO_STATUS = 10,
   WARNING_STATUS = 11,
   ERROR_STATUS = 12,
   TELEMETRY_VALUE_REGISTRATION = 20,
   PARAMETER_REGISTRATION = 21,
   TELEMETRY_GROUP_DEFINTION = 30,
   TELEMETRY_GROUP_UPDATE = 31,
   HEARTBEAT_REQUEST = 40,
   HEARTBEAT_RESPONSE = 41,
   PARAMETER_SET_REQUEST = 50,
   PARAMETER_SET_CONFIRMATION = 51,
   PARAMETER_SET_LOCK_REQUEST = 52,
   PARAMETER_SET_LOCK_CONFIRMATION = 53,
   FIELD_GET_REQUEST = 60,
   FIELD_GET_RESPONSE = 61,
   FIELD_ID_LOOKUP_REQUEST = 62,
   FIELD_ID_LOOKUP_RESPONSE = 63,
}
#endif //MESSAGETYPE_H